---
# Neural collapse config file. All must be specified
Model:
  model-name: None            # Name of model in "our_models"
  embedding-layers: []        # Intermediate layers to use for NC loss with weightings. "^" used to indicate start of network.

Data:
  dataset-id: None       # Which dataset-getter to use. Note that shapes are provided by the dataset
  batch-size: 128        # Mini-batch size
  do-augmentation: False # Whether to do data augmentation

Optimizer:
  loss: mseloss
  weight-decay: None     # Weight decay
  lr: None               # Learning rate
  lr-decay: 0.1
  lr-decay-steps: 3      # Number of learning rate decay steps
  momentum: 0.9          # Optimizer momentum
  epochs: 350            # Number of epochs to train for
  warmup_epochs: 2       # Number of epochs to do linear lr-warmup for

Logging:
  # When to store weights and calculate measurements
  save-dir: logs/matrix/bigdata_param_search
  # log-interval: 10        # At what interval to log checkpoints. Always includes first 10 epochs
  log-epochs: [0, 1, 2, 3, 5, 10, 20, 30, 40, 50, 60, 80, 100, 125, 150, 175, 200, 225, 250, 275, 300, 325, 350]  # Overrides log-interval

Measurements:
  measures: [Accuracy]

# Matrix for parsing into multiple configs to run with slurm
# Parsed as follows:
## All innermost values (leaves)  must be given in a list.
## For the current dictionairy level:
##   Any key other than "_Exclusive" is parsed and the innermost list of that key is used in the matrix.
##   If the key is _Exclusive, assume mutual exclusivity within the list of its contents,
##   and choose one of them to parse as another equivalent dictionary of values.
Matrix:
  _Exclusive:
    mlp_xlarge:
      Model:
        model-name: [mlp_xlarge]
        # embedding-layers: [[fc]]
      # Measurements:
      #   measures: [True]
    mlp_huge:
      Model:
        model-name: [mlp_huge]
        # embedding-layers: [[fc]]
      # Measurements:
      #   measures: [True]
    convnet_deep:
      Model:
        model-name: [convnet_deep]
        # embedding-layers: [[conv, fc]]
      # Measurements:
      #   measures: [Fast_StableRank]
    convnet_deepwide:
      Model:
        model-name: [convnet_deepwide]
        # embedding-layers: [[conv, fc]]
      # Measurements:
      #   measures: [Fast_StableRank]
      Data:
        batch-size: [32]
    resnet152:
      Model:
        model-name: [resnet152]
        # embedding-layers: [[
        #   .conv1, .conv2, .conv3,
        #   ^avgpool, ^fc
        # ]]
      # Measurements:
      #   measures: [Fast_StableRank]
      Data:
        batch-size: [32]
  Data:
    dataset-id: [tinyimagenet, cifar100]  # , stl10, cifar100]
    # dataset-id: [MNIST, FashionMNIST, cifar10, svhn]  # , stl10, cifar100]
  Optimizer:
    lr: [1000, 100, 30, 10, 5, 2]
    weight-decay: [1.e-8]
    # weight-decay: [5.e-4, 2.e-3, 1.e-4]
...
